/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_deaod_jstormlib_MPQArchive */

#ifndef _Included_de_deaod_jstormlib_MPQArchive
#define _Included_de_deaod_jstormlib_MPQArchive
#ifdef __cplusplus
extern "C" {
#endif
#undef de_deaod_jstormlib_MPQArchive_MAX_FILE_COUNT_MIN
#define de_deaod_jstormlib_MPQArchive_MAX_FILE_COUNT_MIN 4L
#undef de_deaod_jstormlib_MPQArchive_MAX_FILE_COUNT_MAX
#define de_deaod_jstormlib_MPQArchive_MAX_FILE_COUNT_MAX 524288L
#undef de_deaod_jstormlib_MPQArchive_DEFAULT_MAX_FILE_COUNT
#define de_deaod_jstormlib_MPQArchive_DEFAULT_MAX_FILE_COUNT 4L
/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    createArchive
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_createArchive
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    openArchive
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_openArchive
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    addListFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_addListFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    setLocale
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_setLocale
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getNativeLocale
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getNativeLocale
  (JNIEnv *, jclass);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    flushArchive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_flushArchive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    closeArchive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_closeArchive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    setMaxFileCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_setMaxFileCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    compactArchive
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_compactArchive
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    setCompactCallback
 * Signature: (JLde/deaod/jstormlib/MPQCompactCallback;)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_setCompactCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    openPatchArchive
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_openPatchArchive
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    isPatchedArchive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQArchive_isPatchedArchive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    addFileEx
 * Signature: (JLjava/lang/String;Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQArchive_addFileEx
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    setAddFileCallback
 * Signature: (JLde/deaod/jstormlib/MPQAddFileCallback;)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_setAddFileCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    hasFile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQArchive_hasFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getArchiveNameN
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_deaod_jstormlib_MPQArchive_getArchiveNameN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getUserDataOffsetN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_getUserDataOffsetN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getUserDataHeaderN
 * Signature: (J)Lde/deaod/jstormlib/data/MPQUserDataHeader;
 */
JNIEXPORT jobject JNICALL Java_de_deaod_jstormlib_MPQArchive_getUserDataHeaderN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getUserDataN
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_deaod_jstormlib_MPQArchive_getUserDataN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHeaderOffsetN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_getHeaderOffsetN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHeaderSizeN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getHeaderSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHeaderN
 * Signature: (J)Lde/deaod/jstormlib/data/MPQHeader;
 */
JNIEXPORT jobject JNICALL Java_de_deaod_jstormlib_MPQArchive_getHeaderN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHetTableOffsetN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_getHetTableOffsetN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHetTableSizeN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_getHetTableSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHetHeaderN
 * Signature: (J)Lde/deaod/jstormlib/data/MPQHetHeader;
 */
JNIEXPORT jobject JNICALL Java_de_deaod_jstormlib_MPQArchive_getHetHeaderN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHetTableN
 * Signature: (J)Lde/deaod/jstormlib/data/MPQHetTable;
 */
JNIEXPORT jobject JNICALL Java_de_deaod_jstormlib_MPQArchive_getHetTableN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getBetTableOffsetN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_getBetTableOffsetN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getBetTableSizeN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_getBetTableSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getBetHeaderN
 * Signature: (J)Lde/deaod/jstormlib/data/MPQBetHeader;
 */
JNIEXPORT jobject JNICALL Java_de_deaod_jstormlib_MPQArchive_getBetHeaderN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getBetTableN
 * Signature: (J)Lde/deaod/jstormlib/data/MPQBetTable;
 */
JNIEXPORT jobject JNICALL Java_de_deaod_jstormlib_MPQArchive_getBetTableN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getArchiveSizeN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getArchiveSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getHashTableSizeN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getHashTableSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getBlockTableSizeN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getBlockTableSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getMPQDataN
 * Signature: (J)[Lde/deaod/jstormlib/data/MPQHash;
 */
JNIEXPORT jobjectArray JNICALL Java_de_deaod_jstormlib_MPQArchive_getMPQDataN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getSectorSizeN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getSectorSizeN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    getFilesCountN
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_getFilesCountN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    isReadOnlyN
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQArchive_isReadOnlyN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    verifyFile
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_verifyFile
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    verifyArchive
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_deaod_jstormlib_MPQArchive_verifyArchive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    extractFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_deaod_jstormlib_MPQArchive_extractFile
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    findFirstFile
 * Signature: (JLjava/lang/String;Lde/deaod/jstormlib/data/MPQFindData;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_findFirstFile
  (JNIEnv *, jclass, jlong, jstring, jobject, jstring);

/*
 * Class:     de_deaod_jstormlib_MPQArchive
 * Method:    listFindFirstFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;Lde/deaod/jstormlib/data/MPQFindData;)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQArchive_listFindFirstFile
  (JNIEnv *, jclass, jlong, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
