/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_deaod_jstormlib_MPQCompression */

#ifndef _Included_de_deaod_jstormlib_MPQCompression
#define _Included_de_deaod_jstormlib_MPQCompression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_deaod_jstormlib_MPQCompression
 * Method:    implode
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_deaod_jstormlib_MPQCompression_implode
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQCompression
 * Method:    explode
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_deaod_jstormlib_MPQCompression_explode
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQCompression
 * Method:    compress
 * Signature: ([BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_deaod_jstormlib_MPQCompression_compress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQCompression
 * Method:    decompress
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_deaod_jstormlib_MPQCompression_decompress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
