/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_deaod_jstormlib_MPQComp */

#ifndef _Included_de_deaod_jstormlib_MPQComp
#define _Included_de_deaod_jstormlib_MPQComp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_deaod_jstormlib_MPQComp
 * Method:    implode
 * Signature: ([BLjava/lang/Integer;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQComp_implode
  (JNIEnv *, jclass, jbyteArray, jobject, jbyteArray, jint);

/*
 * Class:     de_deaod_jstormlib_MPQComp
 * Method:    explode
 * Signature: ([BLjava/lang/Integer;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQComp_explode
  (JNIEnv *, jclass, jbyteArray, jobject, jbyteArray, jint);

/*
 * Class:     de_deaod_jstormlib_MPQComp
 * Method:    compress
 * Signature: ([BLjava/lang/Integer;[BIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQComp_compress
  (JNIEnv *, jclass, jbyteArray, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQComp
 * Method:    decompress
 * Signature: ([BLjava/lang/Integer;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQComp_decompress
  (JNIEnv *, jclass, jbyteArray, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
