/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_deaod_jstormlib_MPQFile */

#ifndef _Included_de_deaod_jstormlib_MPQFile
#define _Included_de_deaod_jstormlib_MPQFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    getFileSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQFile_getFileSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    setFilePointer
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_de_deaod_jstormlib_MPQFile_setFilePointer
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    readFile
 * Signature: (J[BILjava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQFile_readFile
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    writeFile
 * Signature: (J[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQFile_writeFile
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    closeFile
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQFile_closeFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    getFileName
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQFile_getFileName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    getFileInfo
 * Signature: (JI[BILjava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQFile_getFileInfo
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jobject);

/*
 * Class:     de_deaod_jstormlib_MPQFile
 * Method:    setFileLocale
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQFile_setFileLocale
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
