/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_deaod_jstormlib_MPQSearch */

#ifndef _Included_de_deaod_jstormlib_MPQSearch
#define _Included_de_deaod_jstormlib_MPQSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_deaod_jstormlib_MPQSearch
 * Method:    findNextFile
 * Signature: (JLde/deaod/jstormlib/data/MPQFindData;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQSearch_findNextFile
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_deaod_jstormlib_MPQSearch
 * Method:    findClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQSearch_findClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_deaod_jstormlib_MPQSearch
 * Method:    listFindNextFile
 * Signature: (JLde/deaod/jstormlib/data/MPQFindData;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQSearch_listFindNextFile
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_deaod_jstormlib_MPQSearch
 * Method:    listFindClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_deaod_jstormlib_MPQSearch_listFindClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_deaod_jstormlib_MPQSearch_SearchType */

#ifndef _Included_de_deaod_jstormlib_MPQSearch_SearchType
#define _Included_de_deaod_jstormlib_MPQSearch_SearchType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
